# Generated by Django 4.2.20 on 2025-04-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AIAnswer',
        ),
        migrations.DeleteModel(
            name='AIQuestion',
        ),
    ]
