# Generated by Django 5.1 on 2025-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sex_education_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
